config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-champagne-lemming.sh
        container: qc.acc_cozy-eggplant-cassowary
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-charcoal-russel.sh
        container: qc.doc_smelly-ivory-squirrel
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-bistre-collie.sh
        container: qc.doc_woozy-russet-kudu
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cornflower-hyena.sh
        container: qc.doc_geeky-flax-bordeaux
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-crimson-millipede.sh
        container: qc.lic_frumpy-amaranth-fish
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-carmine-argentino.sh
        container: qc.met_squirrely-linen-mongrel
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-amber-owl.sh
        container: qc.sty_hilly-apricot-dog
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-buff-millipede.sh
        container: qc.sty_surly-ultramarine-bear
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-burgundy-tetra.sh
        container: qc.sty_droopy-magnolia-lobster
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cobalt-okapi.sh
        container: qc.ver_foggy-seashell-ocelot
timeout: 5400
