config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: main
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.lapis_polite_hawk.sh
        container: qc.acc_rose_bewildered_meerkat
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.caramel_tranquil_otter.sh
        container: qc.doc_horizon_flexible_quokka
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.arctic_fair_kirin.sh
        container: qc.doc_umber_exuberant_gerbil
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.iris_sympathetic_bison.sh
        container: qc.doc_cayenne_independent_jellyfish
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silver_humorous_toad.sh
        container: qc.lic_seafoam_skeptical_capybara
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slate_understanding_otter.sh
        container: qc.met_thistle_supportive_eagle
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.currant_sociable_moth.sh
        container: qc.sty_indigo_inventive_quail
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pine_clever_seahorse.sh
        container: qc.sty_jasmine_sad_turkey
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cinnamon_compassionate_python.sh
        container: qc.sty_teal_enigmatic_tiger
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gold_tenacious_bat.sh
        container: qc.ver_pansy_zealous_cheetah
timeout: 5400
