config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: main
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-charcoal-ladybird.sh
        container: qc.acc_scaly-harlequin-warthog
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-smalt-warthog.sh
        container: qc.doc_skimpy-zucchini-scorpion
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-amaranth-mongoose.sh
        container: qc.doc_stuffy-saffron-rottweiler
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-firebrick-shark.sh
        container: qc.doc_bluesy-xanthic-discus
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-magnolia-mau.sh
        container: qc.lic_gummy-harlequin-orangutan
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-magnolia-rabbit.sh
        container: qc.met_crappy-lime-vulture
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-burgundy-saola.sh
        container: qc.sty_stuffy-linen-macaw
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-charcoal-cheetah.sh
        container: qc.sty_flabby-rose-bee
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-copper-ostrich.sh
        container: qc.sty_homey-fuchsia-ragdoll
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-rose-wildebeest.sh
        container: qc.ver_squeaky-champagne-bullfrog
timeout: 5400
