config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-chartreuse-skunk.sh
        container: qc.acc_flabby-pink-cat
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-coral-squid.sh
        container: qc.doc_sloppy-saffron-monkey
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-lilac-axolotl.sh
        container: qc.doc_snoopy-blue-wolfhound
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-harlequin-cuscus.sh
        container: qc.doc_pokey-orange-liger
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-blue-cow.sh
        container: qc.lic_sleazy-khaki-sloth
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cornflower-loon.sh
        container: qc.met_pretty-seashell-husky
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-saffron-sponge.sh
        container: qc.sty_jumpy-burgundy-beagle
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-ecru-barb.sh
        container: qc.sty_sickly-carmine-dhole
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-buff-tetra.sh
        container: qc.sty_pretty-aquamarine-meerkat
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-purple-worm.sh
        container: qc.ver_jumpy-goldenrod-kudu
timeout: 5400
