config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: main
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-blue-gorilla.sh
        container: qc.acc_sloppy-viridian-mole
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-xanthic-caracal.sh
        container: qc.doc_cloudy-cinnabar-lemming
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-ivory-jaguar.sh
        container: qc.doc_sunny-cerulean-bombay
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-chocolate-hedgehog.sh
        container: qc.doc_shaky-cornflower-squirt
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-plum-paradise.sh
        container: qc.lic_greasy-smalt-armadillo
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-sangria-otter.sh
        container: qc.met_hilly-sangria-axolotl
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-sangria-barnacle.sh
        container: qc.sty_sleazy-grey-eel
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-linen-foxhound.sh
        container: qc.sty_chummy-chocolate-frigatebird
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-purple-bee.sh
        container: qc.sty_sickly-aquamarine-caracal
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-fuchsia-chamois.sh
        container: qc.ver_skimpy-puce-walrus
timeout: 5400
