config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: main
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-green-indri.sh
        container: qc.acc_pokey-silver-tarsier
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-viridian-centipede.sh
        container: qc.doc_bumpy-corn-hippopotamus
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-plum-ibis.sh
        container: qc.doc_skimpy-celadon-elephant
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-amethyst-okapi.sh
        container: qc.doc_jumpy-turquoise-angora
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-gamboge-turkey.sh
        container: qc.lic_cranky-seashell-cattle
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-denim-mouse.sh
        container: qc.met_cranky-turquoise-jellyfish
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-fuchsia-binturong.sh
        container: qc.sty_craggy-turquoise-slug
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-corn-cockroach.sh
        container: qc.sty_tacky-smalt-coyote
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-green-markhor.sh
        container: qc.sty_grumpy-asparagus-goose
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lilac-dogfish.sh
        container: qc.ver_beady-dandelion-squid
timeout: 5400
