config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/nikosT/argo-accounting:
      branch: devel
      repo: https://github.com/nikosT/argo-accounting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/nikosT/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-purple-binturong.sh
        container: qc.acc_geeky-aqua-ocelot
  QC.Doc:
    repos:
      github.com/nikosT/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-corn-paradise.sh
        container: qc.doc_pokey-xanthic-zorse
      github.com/nikosT/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-beige-liger.sh
        container: qc.doc_droopy-dandelion-malamute
      github.com/nikosT/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-amethyst-audemer.sh
        container: qc.doc_pasty-periwinkle-civet
  QC.Lic:
    repos:
      github.com/nikosT/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-carmine-newfoundland.sh
        container: qc.lic_woozy-razzmatazz-bear
  QC.Met:
    repos:
      github.com/nikosT/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-smalt-drever.sh
        container: qc.met_wimpy-carmine-fousek
  QC.Sty:
    repos:
      github.com/nikosT/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-myrtle-insect.sh
        container: qc.sty_ready-champagne-sheepdog
      github.com/nikosT/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-orchid-cockroach.sh
        container: qc.sty_randy-cobalt-scorpion
      github.com/nikosT/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-white-spaniel.sh
        container: qc.sty_beady-lavender-avocet
  QC.Ver:
    repos:
      github.com/nikosT/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-chocolate-newt.sh
        container: qc.ver_pretty-lavender-starfish
timeout: 5400
