config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-persimmon-bandicoot.sh
        container: qc.acc_slaphappy-smalt-fowl
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-lilac-tamarin.sh
        container: qc.doc_snappy-myrtle-owl
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-denim-cougar.sh
        container: qc.doc_chummy-chartreuse-eel
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-emerald-markhor.sh
        container: qc.doc_craggy-aquamarine-chimpanzee
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-platinum-javanese.sh
        container: qc.lic_dorky-emerald-okapi
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-vermilion-bracke.sh
        container: qc.met_hazy-cyan-lizard
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-indigo-frigatebird.sh
        container: qc.sty_silly-chartreuse-lobster
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-salmon-llama.sh
        container: qc.sty_crappy-amethyst-dalmatian
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-eggplant-quetzal.sh
        container: qc.sty_slaphappy-orange-moose
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-celadon-turtle.sh
        container: qc.ver_cheeky-champagne-frog
timeout: 5400
