config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: mdfix
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-cream-chamois.sh
        container: qc.acc_tasty-periwinkle-chameleon
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cerulean-lemur.sh
        container: qc.doc_thirsty-beige-dane
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-salmon-zebra.sh
        container: qc.doc_dorky-purple-squid
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-carmine-numbat.sh
        container: qc.doc_pasty-khaki-hippopotamus
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-white-fousek.sh
        container: qc.lic_cloudy-gamboge-chin
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-azure-cassowary.sh
        container: qc.met_zippy-aquamarine-foxhound
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.randy-magenta-spitz.sh
        container: qc.sty_flabby-ecru-retriever
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-eggplant-mongrel.sh
        container: qc.sty_crappy-emerald-terrier
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-pumpkin-crane.sh
        container: qc.sty_snippy-bistre-woodlouse
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chartreuse-dane.sh
        container: qc.ver_flabby-rose-terrier
timeout: 5400
