config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: main
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cyan-chow.sh
        container: qc.acc_homely-violet-urchin
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-ochre-albatross.sh
        container: qc.doc_baggy-maroon-rabbit
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-magnolia-frise.sh
        container: qc.doc_flabby-flax-shrimp
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-orange-pig.sh
        container: qc.doc_lovely-heliotrope-peccary
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-auburn-ray.sh
        container: qc.lic_chummy-pear-chinook
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-heliotrope-greyhound.sh
        container: qc.met_slaphappy-white-lemming
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-chartreuse-sponge.sh
        container: qc.sty_scanty-carmine-newt
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-razzmatazz-shrimp.sh
        container: qc.sty_homely-turquoise-drever
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-rust-horse.sh
        container: qc.sty_gamy-magenta-angelfish
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-bronze-anteater.sh
        container: qc.ver_snippy-aquamarine-avocet
timeout: 5400
