config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: main
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cyan-shrimp.sh
        container: qc.acc_cheeky-tangerine-bison
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-magenta-butterfly.sh
        container: qc.doc_gimpy-pumpkin-echidna
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-green-walrus.sh
        container: qc.doc_hilly-violet-greyhound
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-charcoal-sponge.sh
        container: qc.doc_blurry-magnolia-shark
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cornflower-zebra.sh
        container: qc.lic_homey-peach-wolfhound
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-aqua-orangutan.sh
        container: qc.met_bumpy-chestnut-starfish
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-myrtle-moorhen.sh
        container: qc.sty_chewy-auburn-harrier
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-brown-mandrill.sh
        container: qc.sty_pasty-peach-macaw
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-aquamarine-hedgehog.sh
        container: qc.sty_slimy-thistle-chimpanzee
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-brown-giraffe.sh
        container: qc.ver_gummy-chocolate-raccoon
timeout: 5400
